<?php 
defined( 'ABSPATH' ) || exit;


// Typography sections start

Redux::set_section(
	$opt_name,
	array(
		'title'  => esc_html__( 'Home Page', 'rmbt_renoteck' ),
      'id'     => 'home_page-typography',
		'desc'   => esc_html__( 'Typography settings', 'rmbt_renoteck' ),
      'customizer_width' => '450',
      'subsection' => true,      
		'icon'   => 'el el-font',
		'fields' => array(
         array(
            'id'        => 'dish_typography-accordion-start',
            'type'      => 'accordion',
            'title'    => esc_html__( '"Dish" Section', 'rmbt_renoteck' ),
            'subtitle'  => 'Set Your Typography Settings for the "Dishes" Section',
            'position'  => 'start',    
            ),

            array(
               'id'                => 'dish_title-typography',
               'title'             => esc_html__( 'Title', 'rmbt_renoteck' ),
               'subtitle'          => 'Set typography for title',
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#ffffff',
                  'font-size'   => '',
                  'font-family' => 'Playfair Display',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.redux_font-dish_title' ),
            ),
            array(
               'id'                => 'dish_subtitle_1-typography',
               'title'             => esc_html__( 'Subtitle 1', 'rmbt_renoteck' ),
               'subtitle'          => 'Set typography for subtitle 1',
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#ffffff',
                  'font-size'   => '',
                  'font-family' => 'Playfair Display',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.dish-title__subtitle-title' ),
            ),
            array(
               'id'                => 'dish_subtitle_2-typography',
               'title'             => esc_html__( 'Subtitle 2', 'rmbt_renoteck' ),
               'subtitle'          => 'Set typography for subtitle 1',
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#fea100',
                  'font-size'   => '',
                  'font-family' => 'Playfair Display',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.dish-title__subtitle-title span' ),
            ),
            array(
               'id'                => 'explore-food-menu_typography',
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#ffffff',
                  'font-size'   => '',
                  'font-family' => 'Playfair Display',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.redux_font-explore_food_menu' ),
            ),

         array(
            'id'        => 'dish_typography-accordion-end',
            'type'      => 'accordion',
            'position'  => 'end'
         ),         
         
         array(
            'id'        => 'about-typography-accordion-start',
            'type'      => 'accordion',
            'title'    => esc_html__( '"About Us" Section', 'rmbt_renoteck' ),
            'subtitle'  => 'Set Your Typography Settings for the "About Us" Section',
            'position'  => 'start',    
            ),

            array(
               'id'                => 'read_revie_1-typography',
               'title'             => esc_html__( 'Read revie 1 typography', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#000000',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.read > div' ),
            ),
            array(
               'id'                => 'read_revie_2-typography',
               'title'             => esc_html__( 'Read revie 2 typography', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#fea100',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.about-row__top-menu .read p' ),
            ),
            array(
               'id'                => 'call_us_1-typography',
               'title'             => esc_html__( 'call us 1 typography', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#000000',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.about-call-us__text' ),
            ),
            array(
               'id'                => 'call_us_2-typography',
               'title'             => esc_html__( 'call us 2 typography', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#fea100',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.about-call-us__text p' ),
            ),
            array(
               'id'                => 'phone_number-typography',
               'title'             => esc_html__( 'Phone number typography', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#000000',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.about-call-us .phone-number' ),
            ),
            array(
               'id'                => 'title_about-typography',
               'title'  => esc_html__( 'Title of "About" section', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#000000',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.about-row__text h2' ),
            ),
            array(
               'id'                => 'text_about-typography',
               'title'  => esc_html__( 'Text of "About" section', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#878d91',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.about-row__text p' ),
            ),
            array(
               'id'                => 'button_about-typography',
               'title'  => esc_html__( 'Button of "About" section', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#ffffff',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.about-row__text-buttons > .button-orange' ),
            ),

         array(
            'id'        => 'about-typography-accordion-end',
            'type'      => 'accordion',
            'position'  => 'end'
         ),


         array(
            'id'        => 'today-typography-accordion-start',
            'type'      => 'accordion',
            'title'    => esc_html__( '"Today" Section', 'rmbt_renoteck' ),
            'subtitle'  => 'Set Your Typography Settings for the "Today" Section',
            'position'  => 'start',    
            ),

            array(
               'id'                => 'today_title-typography',
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#ffffff',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '#today h2' ),
            ),

         array(
            'id'        => 'today-typography-accordion-end',
            'type'      => 'accordion',
            'position'  => 'end'
         ),

         array(
            'id'        => 'clients_section-accordion-start',
            'type'      => 'accordion',
            'title'    => esc_html__( '"Clients" Section', 'rmbt_renoteck' ),
            'subtitle'  => 'Set Your Typography Settings for the "Clients" Section ',
            'position'  => 'start',    
            ),

            array(
                  'id'                => 'clients_section_title-typography',
                  'title'  => esc_html__( 'Clients Section Title', 'rmbt_renoteck' ),
                  'type'              => 'typography',
                  'google'            => true,
                  'font_family_clear' => false,
                  'color_alpha'       => true,
                  'margin-top'        => true,
                  'margin-bottom'     => true,
                  'text-transform'     => true,
                  'letter-spacing'     => true,
                  'word-spacing'     => true,
                  'line-height'     => true,
                  'text-shadow'       => true,
                  'default'           => array(
                     'color'       => '#ffffff',
                     'font-size'   => '',
                     'font-family' => '',
                     'font-weight' => '',
                     'font-style'  => '',
                     'line-height' => '',
                     'margin-top'    => '',
                     'margin-bottom' => '',
                     'shadow-color'       => '',
                     'shadow-horizontal'  => '0',
                     'shadow-vertical'  => '0',
                     'shadow-blur'  => '0',
                  ),
                  'output'            => array( '.slide-body__title' ),
               ),         
            array(
                  'id'                => 'clients_section_text-typography',
                  'title'  => esc_html__( 'Clients Section Text', 'rmbt_renoteck' ),
                  'type'              => 'typography',
                  'google'            => true,
                  'font_family_clear' => false,
                  'color_alpha'       => true,
                  'margin-top'        => true,
                  'margin-bottom'     => true,
                  'text-transform'     => true,
                  'letter-spacing'     => true,
                  'word-spacing'     => true,
                  'line-height'     => true,
                  'text-shadow'       => true,
                  'default'           => array(
                     'color'       => '#ffffff',
                     'font-size'   => '',
                     'font-family' => '',
                     'font-weight' => '',
                     'font-style'  => '',
                     'line-height' => '',
                     'margin-top'    => '',
                     'margin-bottom' => '',
                     'shadow-color'       => '',
                     'shadow-horizontal'  => '0',
                     'shadow-vertical'  => '0',
                     'shadow-blur'  => '0',
                  ),
                  'output'            => array( '.slide-body__text' ),
               ),      
            array(
               'id'                => 'client_name-typography',
               'title'  => esc_html__( 'Client Name', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#ffffff',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.slide-body .name' ),
            ),

         array(
            'id'        => 'clients_section-accordion-end',
            'type'      => 'accordion',
            'position'  => 'end'
         ),            

         array(
            'id'        => 'reserve_section_section-accordion-start',
            'type'      => 'accordion',
            'title'    => esc_html__( '"Reserve your table" Section', 'rmbt_renoteck' ),
            'subtitle'  => 'Set Your Typography Settings for the "Clients" Section ',
            'position'  => 'start',    
            ),

            array(
                  'id'                => 'reserve_section_title-typography',
                  'title'  => esc_html__( 'Title of Section "Reserve your table"', 'rmbt_renoteck' ),
                  'type'              => 'typography',
                  'google'            => true,
                  'font_family_clear' => false,
                  'color_alpha'       => true,
                  'margin-top'        => true,
                  'margin-bottom'     => true,
                  'text-transform'     => true,
                  'letter-spacing'     => true,
                  'word-spacing'     => true,
                  'line-height'     => true,
                  'text-shadow'       => true,
                  'default'           => array(
                     'color'       => '#14141d',
                     'font-size'   => '',
                     'font-family' => '',
                     'font-weight' => '',
                     'font-style'  => '',
                     'line-height' => '',
                     'margin-top'    => '',
                     'margin-bottom' => '',
                     'shadow-color'       => '',
                     'shadow-horizontal'  => '0',
                     'shadow-vertical'  => '0',
                     'shadow-blur'  => '0',
                  ),
                  'output'            => array( '#reserve h2' ),
               ),         
            array(
                  'id'                => 'reserve_section_form-typography',
                  'title'  => esc_html__( 'Text of form of the "Reserve your table" section', 'rmbt_renoteck' ),
                  'type'              => 'typography',
                  'google'            => true,
                  'font_family_clear' => false,
                  'color_alpha'       => true,
                  'margin-top'        => true,
                  'margin-bottom'     => true,
                  'text-transform'     => true,
                  'letter-spacing'     => true,
                  'word-spacing'     => true,
                  'line-height'     => true,
                  'text-shadow'       => true,
                  'default'           => array(
                     'color'       => '#363d43',
                     'font-size'   => '',
                     'font-family' => '',
                     'font-weight' => '',
                     'font-style'  => '',
                     'line-height' => '',
                     'margin-top'    => '',
                     'margin-bottom' => '',
                     'shadow-color'       => '',
                     'shadow-horizontal'  => '0',
                     'shadow-vertical'  => '0',
                     'shadow-blur'  => '0',
                  ),
                  'output'            => array( '.reserve-form__input' ),
               ),      
            array(
               'id'                => 'button_label-typography',
               'title'  => esc_html__( 'The label of the button', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#ffffff',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.reserve-call-us > a' ),
            ),     
            array(
               'id'                => 'reservation_text-typography',
               'title'  => esc_html__( 'The text for a reservation', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#000000',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.reserve-call-us p' ),
            ),     
            array(
               'id'                => 'reservation_text_2-typography',
               'title'  => esc_html__( 'The second  text for a reservation', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#fc629b',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.reserve-call-us p > span' ),
            ),    
            array(
               'id'                => 'reservation_phone_number-typography',
               'title'  => esc_html__( 'The phone number for a reservation', 'rmbt_renoteck' ),
               'type'              => 'typography',
               'google'            => true,
               'font_family_clear' => false,
               'color_alpha'       => true,
               'margin-top'        => true,
               'margin-bottom'     => true,
               'text-transform'     => true,
               'letter-spacing'     => true,
               'word-spacing'     => true,
               'line-height'     => true,
               'text-shadow'       => true,
               'default'           => array(
                  'color'       => '#14141d',
                  'font-size'   => '',
                  'font-family' => '',
                  'font-weight' => '',
                  'font-style'  => '',
                  'line-height' => '',
                  'margin-top'    => '',
                  'margin-bottom' => '',
                  'shadow-color'       => '',
                  'shadow-horizontal'  => '0',
                  'shadow-vertical'  => '0',
                  'shadow-blur'  => '0',
               ),
               'output'            => array( '.reserve-call-us__tel > a' ),
            ),

         array(
            'id'        => 'clients_section-accordion-end',
            'type'      => 'accordion',
            'position'  => 'end'
         ),          





         
		),
	)
);
